server:
  port: 8762
spring:
  application:
    name: design-mode

eureka:
  instance:
    #eureka客户端需要多长时间发送心跳给eureka服务器，表明他仍然或者，默认30秒
    lease-renewal-interval-in-seconds: 5
    #eureka服务器在接受到实力的最后一次发出的心跳后，需要等待多久才可以将此实力删除
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      company-name: eureka
  client:
    registry-fetch-interval-seconds: 30
    serviceUrl:
      defaultZone: http://localhost:8788/eureka/
